spring:
  application:
    name: openshift-spring-boot-service
  cloud:
    kubernetes:      
      reload:
        enabled: true
  cache:  
    cache-names: helloCache    
    caffeine:
      spec: expireAfterAccess=5s
management:
  endpoint:
    refresh:      
      enabled: true
    restart: 
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
service:
  message: "${SERVICE_MESSAGE:Hi there, this is the default message.}"
