spring:
  application:
    name: openshift-spring-boot-service
  cloud:
    kubernetes:      
      reload:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
service:
  message: "${SERVICE_MESSAGE:Hi there, this is the default message.}"
